variables:
  IMAGE_NAME: vmoroza/portrait_photo
  IMAGE_TAG: tg-bot-1.0

build_image:
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker compose build
    - docker push $IMAGE_NAME:$IMAGE_TAG
