variables:
  IMAGE_NAME: vmoroza/portrait_photo
  IMAGE_TAG: tg-bot-1.0

stages:
  - build
  - deploy

build_image:
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo $REGISTRY_USER
    - echo $REGISTRY_PASSWORD
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker compose build
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SERVER_SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SERVER_SSH_KEY vmoroz@130.193.51.46 "
      docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD &&
      docker ps -aq | xargs docker stop | xargs docker rm &&
      docker run -d $IMAGE_NAME:$IMAGE_TAG"
