from enum import Enum


class OrderStatus(Enum):
    PREPARATION = "PREPARATION"
    PAYMENT_APPROVAL_REQUIRED = "PAYMENT APPROVAL REQUIRED"
    PAYMENT_APPROVED = "PAYMENT APPROVED"
    READY_TO_PROCESS = "READY TO PROCESS"
    AWAITING_RESULTS_FROM_AI = "AWAITING RESULTS FROM AI"
    PROCESSED_IMAGES_UPLOADED = "PROCESSED IMAGES UPLOADED"
    DONE = "DONE"
    CANCELED = "CANCELED"


class ImageType(Enum):
    RAW = "RAW"
    PROCESSED = "PROCESSED"